title: Default Page

tabs:
    content:
        label: Content
        icon: text
        columns:
          - width: 2/3
            sections:
                content:
                    type: fields
                    fields:
                        subtitle:
                            type: text
                            label: Subtitle
                        featuredimage:
                            extends: fields/image
                            label: Featured Image
                            width: 1/2
                        headerimage:
                            extends: fields/image
                            label: Header Image
                            width: 1/2
                        text:
                            extends: fields/mideditor

          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
    seo: tabs/seo
